import type { ContentSection, GuidePageData } from './types';
import { related } from './types';

const checked = 'Live Early Access · checked Aug 26, 2026';

function links(...items: Array<[string, string]>) {
  return items.map(([href, label]) => ({ href, label }));
}

function standardRelated(items: Array<[string, string, string]>) {
  return items.map(([href, label, description]) => related(href, label, description));
}

const soloSections: ContentSection[] = [
  {
    id: 'official-support',
    heading: 'Solo is officially supported',
    paragraphs: [
      'Steam lists Single-player alongside Online Co-op, so solo is a supported way to play rather than an offline workaround. The run still revolves around finding valuables, controlling threats, moving awkward objects, and returning enough loot to advance.',
      'Supported does not mean identical. On Aug 21 the developers separated solo and team balance so quota, shop price and stock, item counts, and enemy spawns can be tuned for different crew sizes.',
    ],
    links: links(['/beginner-guide', 'Start with the current beginner route'], ['/gameplay', 'Review the live gameplay loop']),
  },
  {
    id: 'balance-board',
    heading: 'Solo vs co-op live balance board',
    paragraphs: ['The official patches confirm separate tuning categories but do not publish a permanent numeric sheet for every quota or shop item. Treat the split as a system, not a promise that solo is always easier.'],
    table: {
      headers: ['System', 'Solo', 'Co-op'],
      rows: [
        ['Floor/downed time', '25 seconds', '15 seconds'],
        ['Quota', 'Separately balanced', 'Separately balanced'],
        ['Shop', 'Separate price/stock tuning; Rupor removed', 'Team balance applies'],
        ['Items and enemies', 'Separate count/spawn tuning', 'Team count/spawn tuning'],
      ],
    },
  },
  {
    id: 'shop',
    heading: 'The solo store changed again on Aug 26',
    paragraphs: [
      'The Aug 26 update rebalanced the solo store and removed Rupor from it. That is the safe current statement; no checked official source publishes a full solo price table, so this guide does not freeze volatile values into evergreen advice.',
      'Plan purchases around the run in front of you. Prioritize tools you can actually carry and use, then revisit the current store after a patch rather than relying on a launch-week shopping list.',
    ],
    links: links(['/items-and-weapons', 'Open the current item hub'], ['/golden-weapons', 'Check Golden Weapon evidence']),
  },
  {
    id: 'hauling',
    heading: 'Hauling is lighter, but still a solo risk',
    paragraphs: [
      'Large objects became about 26% lighter on Aug 26. That should reduce some friction, but it does not remove the exposure created by dragging loot, watching the route, and handling monsters without another player covering you.',
      'Stage large pieces near a known return line, keep escape space around the cart, and split breakable valuables when the current object permits it. These are conservative run habits, not hidden movement statistics.',
    ],
    image: { src: '/images/items/hauling-cart.png', alt: 'Official empty hauling cart beside a boat', caption: 'Official EA media · hauling cart by the shore' },
  },
  {
    id: 'threats',
    heading: 'Threat identification matters more alone',
    paragraphs: [
      'The Ear reacts to sound, the Sleeper should be left undisturbed, the Mimic disguises itself, and the Siren now has a pull sound plus restored knockback. These are different problems, so one universal “run away” rule wastes valuable reaction time.',
      'Use the rule-based Monster Finder when you remember a clue but not a name. It only returns records whose stored behavior tags match every clue you select.',
    ],
    links: links(['/tools/monster-finder', 'Identify the threat'], ['/monsters/ear', 'Ear counterplay'], ['/monsters/siren', 'Siren patch cues']),
  },
  {
    id: 'downed',
    heading: 'Solo downed time is 25 seconds',
    paragraphs: [
      'The Aug 26 patch sets the solo floor/downed time to 25 seconds and co-op to 15. It does not publish every revival animation, stamina cost, or recovery edge case, so the timer is the only exact value treated as current here.',
      'Give yourself room before committing to a heavy interaction. In co-op, players report that moving downed friends can collide with stamina pressure; that is a problem signal, not an official numeric rule.',
    ],
    links: links(['/revive-guide', 'Open the downed-player guide']),
  },
  {
    id: 'when-coop',
    heading: 'When Quick Join may be the better plan',
    paragraphs: [
      'If hauling coverage, threat calls, or repeated solo pressure are stopping progress, Quick Join offers a public-lobby path instead of forcing the same run. Public lobbies became enabled by default on Aug 21.',
      'If the search returns no session, use the focused No Game Found order: same version, Steam online state, lobby visibility, one comparison connection method, then one clean restart and file verification.',
    ],
    links: links(['/coop/quick-join', 'Use Quick Join'], ['/coop/no-game-found', 'Fix No Game Found']),
  },
];

export const expansionPages: GuidePageData[] = [
  {
    route: '/solo-guide',
    title: 'Last Pirates: Die Together Solo Guide — Balance, Quota & Survival',
    h1: 'Last Pirates: Die Together Solo Guide',
    description: 'A current solo guide covering separate balance, quota and shop context, the 25-second downed timer, hauling changes, threats, and when to use Quick Join.',
    eyebrow: 'S-tier · live solo strategy',
    directAnswer: [
      'Last Pirates: Die Together officially supports solo play. Since Aug 21, solo and team runs have separate tuning for quota, shop prices and stock, item counts, and enemy spawns; the exact values can still change by build.',
      'The Aug 26 patch gives solo players 25 seconds on the floor versus 15 in co-op, makes large objects about 26% lighter, rebalances the solo store, and removes Rupor from that store. This guide separates those official facts from player-reported difficulty.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Solo Guide' }],
    heroImage: { src: '/images/maps/ship-official.jpg', alt: 'Official crew hauling scene in the Ship location', assetId: 'ship-current-official' },
    sections: soloSections,
    faqs: [
      { question: 'Can you play Last Pirates solo?', answer: 'Yes. Steam currently lists Single-player and the developers now tune solo separately from team play.' },
      { question: 'What is the solo downed timer?', answer: 'The official Aug 26 patch sets solo floor time to 25 seconds; co-op is 15 seconds.' },
      { question: 'Is Rupor in the solo store?', answer: 'The Aug 26 notes say Rupor was removed from the solo store.' },
      { question: 'Does separate balance guarantee easier runs?', answer: 'No. It confirms independent tuning categories, not a guaranteed difficulty level for every build or player.' },
    ],
    sourceIds: ['S01', 'S16', 'S17', 'S18'],
    related: standardRelated([
      ['/beginner-guide', 'Beginner guide', 'Learn the live run loop before specializing.'],
      ['/tools/monster-finder', 'Monster Finder', 'Match a threat from observed behavior.'],
      ['/revive-guide', 'Revive guide', 'Understand the current floor timers.'],
      ['/items-and-weapons', 'Items & weapons', 'Plan around current store evidence.'],
    ]),
  },
  {
    route: '/golden-weapons',
    title: 'Last Pirates Golden Weapons Guide — Golden Sword & Hand Cannon',
    h1: 'Golden Weapons in Last Pirates: Die Together',
    description: 'A source-checked guide to the Golden Sword and Golden Hand Cannon introduced Aug 26, including what top tier means and which exact stats remain unknown.',
    eyebrow: 'S-tier · Aug 26 arsenal',
    directAnswer: [
      'The Aug 26 update added two Golden Weapons: the Golden Sword and Golden Hand Cannon. The official post gives each a dedicated model, texture, and icon and places them at the top of the current weapon tier list.',
      '“Top tier” is a relative official label, not permission to invent exact damage, price, ammo, or durability. The post says they are pricier and meaner; all exact fields remain unknown until current first-party evidence publishes them.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Items & Weapons', href: '/items-and-weapons' }, { label: 'Golden Weapons' }],
    heroImage: { src: '/images/items/golden-sword.png', alt: 'Official Golden Sword render', assetId: 'golden-sword-official' },
    sections: [
      { id: 'introduced', heading: 'Introduced in the Aug 26 update', paragraphs: ['Golden Weapons arrived in the newest official patch found during the Aug 26 research gate. They are a current Early Access addition, not a roadmap promise or a Demo-era item.', 'Both weapons received their own model, texture, and icon. That makes the two identities explicit even though the announcement does not expose a stat sheet.'], links: links(['/updates', 'Read the canonical patch timeline']) },
      { id: 'sword', heading: 'Golden Sword', paragraphs: ['The Golden Sword is the melee member of the pair. The official post calls the Golden Weapons top-tier and “pricier and meaner,” but it does not state a damage number, swing speed, durability value, or exact store cost.', 'Judge the weapon in the current client and treat any numeric claim without a dated current source as unverified.'], image: { src: '/images/items/golden-sword.png', alt: 'Golden Sword official model', caption: 'Official Aug 26 Golden Sword model' } },
      { id: 'cannon', heading: 'Golden Hand Cannon', paragraphs: ['The Golden Hand Cannon is the ranged member. The announcement provides its identity and tier position but no safe exact ammo count, reload value, damage, durability, or purchase price.', 'A screenshot from another build cannot silently fill those gaps because balance may change independently of the model.'], image: { src: '/images/items/golden-hand-cannon.png', alt: 'Golden Hand Cannon official model', caption: 'Official Aug 26 Golden Hand Cannon model' } },
      { id: 'top-tier', heading: 'What “top tier” safely means', paragraphs: ['It means the developer currently places the pair at the top of its weapon tier list. It does not prove that every situation favors them, that a single hit has a fixed outcome, or that the ranking will survive a later balance pass.'], table: { headers: ['Field', 'Current evidence'], rows: [['Identity', 'Golden Sword and Golden Hand Cannon'], ['Tier', 'Officially described at the top'], ['Price', 'Higher in general; exact value unknown'], ['Damage / ammo / durability', 'Exact values not published in the checked source']] } },
      { id: 'store', heading: 'Current store context', paragraphs: ['The same patch rebalanced the solo store and removed Rupor from it. That provides useful build context but does not say that Golden Weapon availability, price, or stock is identical in solo and co-op.', 'Check the live store before planning a run around either weapon. Record the build if you report a changed value.'], links: links(['/solo-guide', 'See current solo store context'], ['/items-and-weapons', 'Return to the item hub']) },
      { id: 'unknowns', heading: 'Unknown fields stay visible as unknown', paragraphs: ['This guide intentionally leaves exact price, damage, ammo, durability, and any hidden drop rule blank. Search demand is not evidence, and a specific number would become misleading as soon as a hotfix changes it.', 'If a future official patch publishes one of those fields, the source registry and page can be updated together.'] },
      { id: 'history', heading: 'Patch history', paragraphs: ['Aug 26 is the introduction point for both Golden Weapons. No newer official item appeared in the 20 most recent Steam news entries checked for this release.', 'Later changes belong on the durable Updates page and here, rather than on one thin page per minor hotfix.'], links: links(['/updates', 'Follow later weapon changes']) },
    ],
    faqs: [
      { question: 'What are the Golden Weapons?', answer: 'The Golden Sword and Golden Hand Cannon, introduced in the Aug 26 update.' },
      { question: 'How much do they cost?', answer: 'The checked official announcement does not publish exact prices.' },
      { question: 'Are exact damage and ammo values known?', answer: 'Not from the current official source, so this guide does not invent them.' },
    ],
    sourceIds: ['S17'],
    related: standardRelated([
      ['/items-and-weapons', 'Items & weapons', 'Return to the current equipment hub.'],
      ['/solo-guide', 'Solo guide', 'Understand separate shop tuning.'],
      ['/updates', 'Updates', 'Follow durable patch history.'],
      ['/monsters', 'Monsters', 'See what the latest balance pass changed.'],
    ]),
  },
  {
    route: '/monsters/ear',
    title: 'Ear Monster Guide — Sound, Hearing Range & Counterplay',
    h1: 'Ear Monster Guide',
    description: 'Identify the Ear monster by its sound-based behavior, understand the Aug 19 attack and hearing reductions, and use evidence-safe counterplay without fake distances.',
    eyebrow: 'Monster record · sound',
    directAnswer: [
      'Ear is a blind, sound-driven Early Access monster. The official launch post says it cannot see and comes swinging when players make noise, making audio discipline the strongest verified identification clue.',
      'The Aug 19 hotfix reduced both its attack range and hearing range. No checked source publishes meter values, so practical counterplay should focus on avoiding unnecessary sound and preserving escape room rather than memorizing invented distances.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Monsters', href: '/monsters' }, { label: 'Ear' }],
    heroImage: { src: '/images/monsters/ear-official.jpg', alt: 'Official image of the Ear monster in a Castle room', assetId: 'ear-current-official' },
    sections: [
      { id: 'identify', heading: 'How to identify Ear', paragraphs: ['The creature’s official identity is tied to hearing rather than sight. If a threat reacts when the crew creates sound but does not behave like a sight hunter, Ear is the current typed-registry match.', 'The Monster Finder uses the same sound tag as this page and the monsters hub. It does not guess from appearance alone.'], links: links(['/tools/monster-finder', 'Match observed monster clues']) },
      { id: 'behavior', heading: 'Verified behavior', paragraphs: ['The launch announcement states that Ear cannot see, hears everything, and comes swinging when noise is made. That supports a sound trigger; it does not reveal a complete aggro model, movement speed, or a guaranteed stealth threshold.', 'Other nearby creatures can still react independently, so silence around Ear is risk reduction rather than immunity.'] },
      { id: 'aug19', heading: 'Aug 19 range and hearing nerf', paragraphs: ['The Day One Hotfix reduced Ear’s attack range and hearing range. Both changes are current patch history, but the note does not publish before-and-after meters.', 'A later build could tune the values again. The durable claim is the direction of the Aug 19 change, not a fabricated radius.'], table: { headers: ['Date', 'Verified change', 'Unknown'], rows: [['Aug 19, 2026', 'Smaller attack range', 'Exact distance'], ['Aug 19, 2026', 'Smaller hearing range', 'Exact hearing radius']] } },
      { id: 'counterplay', heading: 'Evidence-safe counterplay', paragraphs: ['Reduce optional noise, avoid testing the boundary at close range, and decide the crew’s movement order before interacting with nearby loot. Give the current attack space rather than treating the nerf as harmlessness.', 'In co-op, call the identification briefly and avoid several players creating competing sound. In solo, stage the hauling route before touching a noisy or awkward object.'], links: links(['/solo-guide', 'Apply the clue in solo runs'], ['/beginner-guide', 'Review live beginner priorities']) },
      { id: 'not-known', heading: 'What is not verified', paragraphs: ['No current official source provides hearing meters, attack meters, cooldown, health, damage, spawn probability, or a complete map-specific table. These fields stay absent instead of being backfilled from community guesses.', 'The official image proves appearance context, not numerical mechanics.'] },
      { id: 'record', heading: 'Registry and current scope', paragraphs: ['Ear is an EA-confirmed entity with a sound behavior tag, an Aug 19 patch record, and a detail route. The combined site roster is not presented as complete.', 'Use the hub to compare Ear with sight, disguise, disturbed, pull-sound, and group-context threats.'], links: links(['/monsters', 'Return to the live monster hub'], ['/monsters/anchorer', 'Compare the Anchorer'], ['/monsters/siren', 'Compare the Siren']) },
    ],
    faqs: [
      { question: 'Does Ear see players?', answer: 'The official launch post says Ear cannot see and hunts by sound.' },
      { question: 'What changed on Aug 19?', answer: 'Its attack range and hearing range were reduced.' },
      { question: 'What is Ear’s exact hearing distance?', answer: 'No exact distance is published in the checked official sources.' },
    ],
    sourceIds: ['S11', 'S13'],
    related: standardRelated([
      ['/monsters', 'Monsters hub', 'Compare current threat records.'],
      ['/tools/monster-finder', 'Monster Finder', 'Identify a creature from behavior clues.'],
      ['/beginner-guide', 'Beginner guide', 'Build sound discipline into the run.'],
      ['/solo-guide', 'Solo guide', 'Plan threat handling without a lookout.'],
    ]),
  },
  {
    route: '/monsters/anchorer',
    title: 'Anchorer Guide — Loot Hiding, Attack Speed & Survival',
    h1: 'Anchorer Monster Guide',
    description: 'A current Anchorer guide covering its loot-hiding finder clue, official sight-and-hook behavior, the Aug 20 attack-speed reduction, and safe survival decisions.',
    eyebrow: 'Monster record · hook threat',
    directAnswer: [
      'Anchorer is a current Early Access monster associated with loot hiding in the approved field taxonomy. The official launch description independently confirms that it is deaf but sharp-eyed and can hook a player from range, reel them in, and throw them.',
      'The Aug 20 Fresh Fixes patch reduced Anchorer attack speed. No checked source gives a cooldown, meter distance, damage value, or exact disguise rule, so this guide uses visual checking, sightline control, and spacing without pretending to know those numbers.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Monsters', href: '/monsters' }, { label: 'Anchorer' }],
    heroImage: { src: '/images/monsters/anchorer-official.png', alt: 'Official image of Anchorer pulling a pirate with a chain', assetId: 'anchorer-current-official' },
    sections: [
      { id: 'identify', heading: 'Identification clues', paragraphs: ['The approved finder clue is “hides among loot.” Once active, the stronger official description is sight-driven: Anchorer is deaf, sharp-eyed, and uses a hook-and-reel attack.', 'Treat a suspicious loot silhouette as a reason to inspect from safety, not as proof that every object can become an Anchorer.'], links: links(['/tools/monster-finder', 'Use the transparent clue matcher']) },
      { id: 'hook', heading: 'Official hook behavior', paragraphs: ['The launch post says Anchorer hooks from range, reels the target in, and throws them, and warns that mid distance is especially dangerous. The official media shows the chain attack in progress.', 'That supports breaking sightlines and avoiding complacent mid-range observation. It does not establish exact range, tracking, or escape timing.'] },
      { id: 'aug20', heading: 'Aug 20 attack-speed reduction', paragraphs: ['Fresh Fixes reduced Anchorer attack speed. This is a balance direction, not an immunity window: the attack remains part of the live threat identity.', 'Because the note gives no before-and-after timing, do not convert “slower” into a fixed count or a guaranteed reaction window.'], table: { headers: ['Evidence', 'Confirmed', 'Not published'], rows: [['EA launch', 'Deaf, sharp-eyed, hook/reel/throw', 'Exact range and damage'], ['Aug 20', 'Attack speed reduced', 'Exact cooldown or wind-up']] } },
      { id: 'survival', heading: 'Safe survival plan', paragraphs: ['Scan dense loot from an angle with a clear retreat, avoid holding a straight mid-distance sightline, and do not bunch the whole crew where one pull creates a collision. If the hook starts, prioritize space rather than another loot interaction.', 'Solo players should set down large haul objects before inspecting a suspicious cluster. Co-op crews can separate observer and hauler roles.'], links: links(['/solo-guide', 'Solo hauling and threat choices'], ['/loot-and-extraction', 'Current hauling guide']) },
      { id: 'unknowns', heading: 'Unknown fields', paragraphs: ['Current official evidence does not publish Anchorer health, damage, spawn rate, map frequency, attack meters, exact speed, or a complete list of objects it can resemble. Those omissions are deliberate.', 'The page will record later official changes by date instead of silently rewriting the original evidence.'] },
      { id: 'compare', heading: 'Compare it with other clue patterns', paragraphs: ['Ear is sound-driven, Mimic uses teammate disguise, Sleeper wakes when disturbed, and Siren now exposes a pull sound. Anchorer’s official identity is sight and hook pressure.', 'Use the hub for the wider roster and remember that the combined current records are not claimed to be complete.'], links: links(['/monsters', 'Return to Monsters'], ['/monsters/ear', 'Ear guide'], ['/monsters/mimic', 'Mimic guide']) },
    ],
    faqs: [
      { question: 'What does Anchorer do?', answer: 'Official launch notes describe a deaf, sharp-eyed creature that hooks, reels in, and throws players.' },
      { question: 'What changed on Aug 20?', answer: 'Its attack speed was reduced.' },
      { question: 'Is an exact hook range known?', answer: 'No exact range is published in the checked sources.' },
    ],
    sourceIds: ['S11', 'S15'],
    related: standardRelated([
      ['/monsters', 'Monsters hub', 'Compare the current roster evidence.'],
      ['/tools/monster-finder', 'Monster Finder', 'Match loot-hiding and other clues.'],
      ['/beginner-guide', 'Beginner guide', 'Build safer inspection habits.'],
      ['/solo-guide', 'Solo guide', 'Handle hauling and threat coverage alone.'],
    ]),
  },
  {
    route: '/monsters/siren',
    title: 'Siren Guide — Pull Sound, Knockback & How to Survive',
    h1: 'Siren Monster Guide',
    description: 'A current Siren guide focused on the Aug 26 pull sound cue and restored knockback, with transparent unknowns for range, cooldown, damage, and spawn rules.',
    eyebrow: 'Monster record · Aug 26 cue',
    directAnswer: [
      'Siren is a current patch-observed threat. The Aug 26 update added a sound when the Siren pulls and restored its knockback, giving players one verified audio cue and one verified displacement behavior to plan around.',
      'The patch does not publish Siren range, cooldown, damage, health, or spawn probability. Listen for the pull cue, protect your route and footing, and avoid advice that turns those unknown fields into confident numbers.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Monsters', href: '/monsters' }, { label: 'Siren' }],
    heroImage: { src: '/images/game/feature-survival.webp', alt: 'Official Last Pirates survival feature art', assetId: 'feature-survival' },
    sections: [
      { id: 'current', heading: 'Current verified Siren state', paragraphs: ['The newest official patch found at the research gate explicitly names Siren twice: a pull sound was added and knockback was restored. These details are current as of the Aug 26 China-date release.', 'The update does not provide a complete behavior dossier, so this page stays centered on those two observable hooks.'] },
      { id: 'pull-sound', heading: 'Use the pull sound as a warning', paragraphs: ['A sound cue can give the crew information before or during a pull, but the note does not define its audible distance or whether other scene audio can mask it.', 'When the cue occurs, stop optional hauling actions, identify safe footing, and communicate the direction if the crew can do so without creating more confusion.'], links: links(['/tools/monster-finder', 'Match the pull-sound clue']) },
      { id: 'knockback', heading: 'Knockback is restored', paragraphs: ['Restored knockback means positioning matters again. Avoid treating narrow edges, moving equipment, or crowded loot lanes as safe just because an earlier build behaved differently.', 'No official force value is published. “Restored” proves the effect returned, not how far every target moves.'] },
      { id: 'counterplay', heading: 'Evidence-safe survival plan', paragraphs: ['Keep an exit line, avoid stacking the crew in one displacement lane, and pause a heavy carry when the audio cue starts. Those habits reduce exposure without relying on a fake cooldown.', 'Solo players should favor stable footing and shorter hauling stages. Co-op crews can call the cue and separate recovery space.'], links: links(['/solo-guide', 'Plan solo threat handling'], ['/revive-guide', 'Prepare for downed-player recovery']) },
      { id: 'unknowns', heading: 'Do not invent range or cooldown', paragraphs: ['The checked patch does not state pull range, cooldown, damage, health, spawn map, spawn probability, immunity timing, or exact knockback distance. Community observations can help identify questions but cannot fill the numeric fields.', 'If the client changes after another update, record the build and compare it with a dated official note.'] },
      { id: 'history', heading: 'Patch history and related threats', paragraphs: ['Aug 26 is the current durable Siren record: pull sound added and knockback restored. The monsters hub also tracks Headcrab and Man in Shadows reductions from the same patch.', 'Use the finder for clue matching, then return to the hub for the non-complete roster and patch-observed threat section.'], links: links(['/monsters', 'Open the live monster hub'], ['/monsters/ear', 'Compare a sound-hunting threat'], ['/updates', 'Read the Aug 26 summary']) },
    ],
    faqs: [
      { question: 'What changed for Siren on Aug 26?', answer: 'The patch added a sound for its pull and restored knockback.' },
      { question: 'What is the Siren pull range?', answer: 'The checked official patch does not publish an exact range.' },
      { question: 'Does the finder use Siren clues?', answer: 'Yes. Pull sound and knockback context are transparent tags in the typed registry.' },
    ],
    sourceIds: ['S17'],
    related: standardRelated([
      ['/monsters', 'Monsters hub', 'See the current patch-observed roster.'],
      ['/tools/monster-finder', 'Monster Finder', 'Match pull-sound and knockback clues.'],
      ['/beginner-guide', 'Beginner guide', 'Prepare a safer live-build run.'],
      ['/solo-guide', 'Solo guide', 'Manage threats without crew coverage.'],
    ]),
  },
  {
    route: '/monsters/mimic',
    title: 'Mimic Guide — Disguise, Reactions & How to Spot It',
    h1: 'Mimic Monster Guide',
    description: 'A source-backed Mimic guide covering teammate disguise, official voice-copy evidence, its attack reaction change, identification discipline, and unknown exact mechanics.',
    eyebrow: 'Monster record · disguise',
    directAnswer: [
      'Mimic is an Early Access monster built to resemble a teammate. The official launch announcement says it can also speak in familiar player voices, so both visual identity and voice alone are unsafe confirmation signals in the current evidence record.',
      'An earlier official patch says the Mimic reacts when attacked. That does not define damage, reaction timing, health, or a universal test; use crew verification and spacing rather than hitting every suspicious teammate at close range.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Monsters', href: '/monsters' }, { label: 'Mimic' }],
    heroImage: { src: '/images/game/steam-page-background.jpg', alt: 'Official Last Pirates key art with crew and shadowed threat', assetId: 'steam-page-background' },
    sections: [
      { id: 'disguise', heading: 'Verified disguise behavior', paragraphs: ['The launch post calls Mimic almost impossible to tell from a real teammate. That supports disguise as the finder tag and justifies a crew-verification habit before approaching an isolated figure.', 'It does not publish the full set of copied cosmetics, movement quirks, or a guaranteed visual tell.'] },
      { id: 'voice', heading: 'Current official evidence includes familiar voices', paragraphs: ['The same official launch announcement explicitly says Mimic can speak in friends’ voices to draw a crewmate closer. This guide retains the claim because current first-party evidence proves it.', 'Voice copying does not mean every voice event is a Mimic. Network voice issues and real teammates remain separate explanations.'], links: links(['/coop', 'Review current co-op voice context']) },
      { id: 'reaction', heading: 'The Mimic reacts when attacked', paragraphs: ['The June 19 official save-system patch also records that Mimic was changed to react when attacked. The note predates EA, while the launch announcement confirms Mimic remains present in EA.', 'The reaction is a history fact, not a published test procedure. No exact reaction time, damage threshold, or safe distance is given.'] },
      { id: 'spot', heading: 'How to reduce identification risk', paragraphs: ['Agree on simple crew context—where each player is going, what they are carrying, and who is isolated—then challenge an unexpected figure from space. Do not let a copied voice pull the entire team into one narrow position.', 'Solo players can still encounter the disguise threat but cannot use teammate confirmation, so preserving distance and an exit is more important than testing a close silhouette.'], links: links(['/solo-guide', 'Solo threat planning'], ['/tools/monster-finder', 'Use the disguise clue']) },
      { id: 'unknowns', heading: 'Unknown mechanics stay unknown', paragraphs: ['No checked source publishes Mimic health, damage, exact reaction, spawn chance, map weighting, copy duration, voice frequency, or a perfect visual tell. Those gaps are displayed instead of filled with folklore.', 'A player clip may be a useful lead for research, but it is not enough to update a confirmed field by itself.'] },
      { id: 'compare', heading: 'Compare disguise with other triggers', paragraphs: ['Ear is tagged for sound reaction, Sleeper for disturbance, Anchorer for the approved loot-hiding clue and official sight/hook behavior, and Siren for pull sound and knockback context.', 'The typed registry ensures the hub, detail pages, and Monster Finder all use the same evidence state.'], links: links(['/monsters', 'Return to Monsters'], ['/monsters/anchorer', 'Compare Anchorer'], ['/monsters/ear', 'Compare Ear']) },
    ],
    faqs: [
      { question: 'Can Mimic copy a teammate?', answer: 'Yes. The official EA launch announcement confirms teammate-like disguise.' },
      { question: 'Can Mimic copy voices?', answer: 'The official EA launch announcement explicitly says it can speak in familiar player voices.' },
      { question: 'How do you prove a figure is Mimic?', answer: 'No perfect universal test is published. Use crew context, distance, and cautious verification.' },
    ],
    sourceIds: ['S08', 'S11'],
    related: standardRelated([
      ['/monsters', 'Monsters hub', 'Compare current entity evidence.'],
      ['/tools/monster-finder', 'Monster Finder', 'Use the disguise behavior tag.'],
      ['/beginner-guide', 'Beginner guide', 'Build safer crew routines.'],
      ['/solo-guide', 'Solo guide', 'Adapt threat verification alone.'],
    ]),
  },
  {
    route: '/coop/no-game-found',
    title: 'Last Pirates No Game Found Fix — Codes, Invites & Quick Join',
    h1: 'Last Pirates: Die Together No Game Found Fix',
    description: 'Fix No Game Found with a safe order for versions, Steam online state, lobby visibility, codes, invites, Quick Join, restart, verification, and reporting.',
    eyebrow: 'Co-op recovery · safe order',
    directAnswer: [
      '“No Game Found” is a current player-reported symptom across lobby codes, Steam invites, and Quick Join. That demand signal does not prove one global server cause, so the fastest useful response is to separate version, Steam presence, lobby visibility, method, and region.',
      'Start by putting the crew on the same current build and confirming Steam is online. Then compare one direct invite, current code, or Quick Join path, retry the intended public/private flow, restart the game and Steam once, verify files, and report exact context if it repeats.',
    ],
    buildContext: checked,
    confidence: 'community-reported',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Co-op', href: '/coop' }, { label: 'No Game Found' }],
    heroImage: { src: '/images/game/feature-coop.webp', alt: 'Official co-op feature strip', assetId: 'feature-coop' },
    sections: [
      { id: 'scope', heading: 'What the error does and does not prove', paragraphs: ['A community report can establish that players see the symptom; it cannot identify the server, region, client state, or lobby configuration behind every occurrence. Treat the words as the start of diagnosis, not the diagnosis itself.', 'Record which method failed before changing anything. A code, Steam invite, and public Quick Join are different comparison paths.'] },
      { id: 'version', heading: '1 · Put every player on the same build', paragraphs: ['Finish Steam updates, confirm everyone launched the full Early Access game rather than the separate Demo, and compare any version string the current client exposes. A mixed crew state must be resolved before region or lobby testing.', 'The Aug 19–26 patch cadence makes stale-client comparisons especially important.'], links: links(['/updates', 'Check the current official patch timeline']) },
      { id: 'steam', heading: '2 · Confirm Steam is online', paragraphs: ['Make sure the host and joiner are signed in, online, and able to receive a fresh Steam invite. If presence itself is stale, a lobby code can appear to be the problem when the session handoff is actually unavailable.', 'Do not disable antivirus, firewall, or account protection for this check.'] },
      { id: 'visibility', heading: '3 · Match public or private intent', paragraphs: ['Public lobbies became enabled by default on Aug 21. Quick Join belongs to public search; a private crew should use the current host invite or code shown by the active lobby.', 'Confirm the host did not recreate the lobby and leave the joiner with an old code. Use one fresh value once rather than stacking requests.'], links: links(['/coop/quick-join', 'Review the live Quick Join feature']) },
      { id: 'compare', heading: '4 · Compare one alternate method', paragraphs: ['If a current code fails, try one direct Steam invite. If an invite fails, compare the current code. If both fail and a public game is acceptable, try one Quick Join search in the intended region.', 'The result narrows the scope: one-method failure, lobby-specific failure, or broader client/session failure. It does not guarantee a server diagnosis.'], table: { headers: ['First failure', 'One comparison'], rows: [['Join code', 'Fresh Steam invite'], ['Steam invite', 'Current lobby code'], ['Quick Join', 'Host-created invite/code if available']] } },
      { id: 'restart', heading: '5 · One clean restart and file verification', paragraphs: ['Exit the game and Steam, reopen Steam, finish any update, and retry once. If the client remains abnormal, use Steam’s normal installed-files verification.', 'Avoid random ports, launch flags, registry edits, save deletion, and broad security changes. They add risk without proving the cause.'] },
      { id: 'report', heading: '6 · Report repeatable context', paragraphs: ['Capture build or update date, region, host/joiner role, intended public/private state, failed method, comparison result, and exact visible text. That is enough to distinguish a search issue from a stale code or invite handoff.', 'The interactive Co-op Troubleshooter produces the same ordered logic with explicit context inputs.'], links: links(['/tools/coop-troubleshooter', 'Build the interactive checklist'], ['/save-and-reconnect', 'Separate mid-run reconnect failures']) },
    ],
    faqs: [
      { question: 'Does No Game Found mean servers are down?', answer: 'Not by itself. The same symptom can follow version, lobby, method, region, or session-state differences.' },
      { question: 'Should I open ports or disable my firewall?', answer: 'No. Start with supported, reversible Steam and lobby checks.' },
      { question: 'What should I report?', answer: 'Build, region, host/joiner role, lobby visibility, connection method, comparison result, and exact error.' },
    ],
    sourceIds: ['S01', 'S07', 'S16', 'S18'],
    related: standardRelated([
      ['/coop', 'Co-op guide', 'Review current public and private crew context.'],
      ['/coop/quick-join', 'Quick Join', 'Use the public-lobby feature path.'],
      ['/tools/coop-troubleshooter', 'Co-op Troubleshooter', 'Generate an ordered checklist.'],
      ['/save-and-reconnect', 'Save & reconnect', 'Handle failures after a run starts.'],
    ]),
  },
  {
    route: '/maps/ship',
    title: 'Last Pirates Ship Map Guide — Titanic, Loot & Current Changes',
    h1: 'Ship Guide in Last Pirates: Die Together',
    description: 'A current Ship location guide covering EA status, tight decks, hauling, the breakable Titanic item, Aug 26 spawn-ship visual refresh, and safe unknowns.',
    eyebrow: 'Current EA location',
    directAnswer: [
      'Ship is one of the two current locations named in the official Early Access launch announcement. The developer describes tight decks, creaking rigging, dark corners, and a loot-hauling run rather than publishing a complete room-by-room map.',
      'The Aug 21 patch added Titanic as a breakable item in Ship levels, and the Aug 26 patch refreshed the spawn ship visually. This guide records those durable changes without inventing spawn points, floor plans, or a guaranteed loot route.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Maps', href: '/maps' }, { label: 'Ship' }],
    heroImage: { src: '/images/maps/ship-official.jpg', alt: 'Official Ship location co-op hauling scene', assetId: 'ship-current-official' },
    sections: [
      { id: 'status', heading: 'Ship is a current EA location', paragraphs: ['The official launch announcement names Ship as a new location in the released Early Access build. That supersedes Silent Cove’s Demo-only location context without making Silent Cove’s indexed archive page disappear.', 'Ship is a current map record; the site still does not claim that two named EA locations prove a complete future map list.'], links: links(['/maps', 'Return to the current map hub'], ['/maps/silent-cove', 'Read the Demo archive context']) },
      { id: 'character', heading: 'Tight decks and dark corners', paragraphs: ['The official description emphasizes tight decks, creaking rigging, and dark corners. Those features support shorter sightlines and careful hauling habits, but they do not reveal a stable floor plan.', 'Use scene landmarks in your current run and communicate changes after patches instead of relying on an invented compass route.'] },
      { id: 'titanic', heading: 'Titanic breakable haul', paragraphs: ['The Aug 21 notes add a Titanic breakable item to Ship levels. The official launch announcement separately confirms that some large valuables can be broken into pieces for carrying.', 'The sources do not publish Titanic value, exact pieces, weight, or guaranteed location, so those fields remain open.'], links: links(['/loot-and-extraction', 'Plan the current extraction loop']) },
      { id: 'hauling', heading: 'Hauling after the Aug 26 weight change', paragraphs: ['Large objects became about 26% lighter in the Aug 26 patch. The change helps hauling generally but does not remove narrow-deck exposure or prove that every object changed equally.', 'Stage the cart where the crew can turn, split permitted breakables, and avoid blocking the same path needed for retreat.'], links: links(['/monkey-cart', 'See current cart and Porter evidence'], ['/solo-guide', 'Adapt hauling for solo']) },
      { id: 'visual', heading: 'Spawn ship visual refresh', paragraphs: ['The Aug 26 update refreshed the visual appearance of the ship where players spawn. This is a presentation change, not evidence of a new map layout or mechanical route.', 'Screenshots from launch and Aug 26 can therefore look different while still referring to the Ship context.'] },
      { id: 'threats', heading: 'Threat context without a fake spawn table', paragraphs: ['Current monster evidence applies at roster level, but the checked sources do not provide a complete Ship-specific spawn matrix. Use observed behavior—sound, disguise, disturbance, pull cue—before assigning a name.', 'The Monster Finder returns only records matching selected stored tags.'], links: links(['/monsters', 'Open the live monster hub'], ['/tools/monster-finder', 'Identify a threat from behavior']) },
    ],
    faqs: [
      { question: 'Is Ship in the current game?', answer: 'Yes. The official EA launch announcement names Ship as a current location.' },
      { question: 'What is Titanic?', answer: 'The Aug 21 patch calls Titanic a breakable item added to Ship levels; exact values are not published.' },
      { question: 'Is there a verified full Ship map?', answer: 'No complete official floor plan or stable spawn route was found in the checked sources.' },
    ],
    sourceIds: ['S11', 'S16', 'S17'],
    related: standardRelated([
      ['/maps', 'Maps hub', 'Compare current and historical locations.'],
      ['/loot-and-extraction', 'Loot & extraction', 'Plan current hauling decisions.'],
      ['/monsters', 'Monsters', 'Identify live threat behavior.'],
      ['/maps/castle', 'Castle guide', 'Compare the other named EA location.'],
    ]),
  },
  {
    route: '/maps/castle',
    title: 'Last Pirates Castle Guide — Current Location, Hazards & Patch Notes',
    h1: 'Castle Guide in Last Pirates: Die Together',
    description: 'A source-checked Castle guide covering current EA status, heavy loot, elevators and funiculars, current visual context, and the boundary between Castle and Mansion notes.',
    eyebrow: 'Current EA location',
    directAnswer: [
      'Castle is a current Early Access location officially described as bigger and colder, with heavy loot and elevators and funiculars used to move through it. Those facts support route planning but not a fabricated room layout.',
      'Official hotfixes mention Mansion balance and a cart/funicular interaction, but the checked sources do not prove that every Mansion note is automatically a Castle-wide rule. This guide connects only the verified transport context and keeps the entity boundary visible.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Maps', href: '/maps' }, { label: 'Castle' }],
    heroImage: { src: '/images/maps/castle-official.jpg', alt: 'Official Castle interior gameplay scene', assetId: 'castle-current-official' },
    sections: [
      { id: 'status', heading: 'Castle is live in Early Access', paragraphs: ['The official EA launch announcement names Castle alongside Ship. The location record is current and should not be merged with the separate Demo-era Silent Cove page.', 'The current announcement is the source for the high-level setting; it does not claim a complete map roster.'], links: links(['/maps', 'Open the map hub'], ['/maps/ship', 'Compare Ship']) },
      { id: 'character', heading: 'Bigger, colder, and built around heavy loot', paragraphs: ['The developer’s description calls Castle bigger and colder and says it is packed with heavy loot. That makes transport and return-line planning central to the location.', 'The Aug 26 reduction makes large objects about 26% lighter, but heavy interaction can still expose a solo player or separate a crew.'], links: links(['/loot-and-extraction', 'Review the current hauling loop'], ['/solo-guide', 'Plan Castle hauling solo']) },
      { id: 'transport', heading: 'Elevators and funiculars', paragraphs: ['The launch post explicitly says elevators and funiculars were added to carry players around Castle’s larger spaces. An Aug 20 patch fixed a cart/funicular problem, supporting the transport connection.', 'The notes do not publish schedules, exact stops, or a route diagram. Treat moving machinery and loaded carts carefully in the current scene.'] },
      { id: 'mansion', heading: 'Castle is not automatically identical to Mansion', paragraphs: ['Fresh Fixes says Mansion boss balance was reworked. The checked wording does not explicitly equate the entire Mansion entity with Castle, so this page does not transfer boss mechanics or a Mansion floor plan into Castle guidance.', 'Only the separately verified Castle transport and setting facts are stated affirmatively.'] },
      { id: 'visual', heading: 'Official visual context', paragraphs: ['The official EA media shows both interior co-op scenes and a foggy Castle exterior. These images are strong evidence of setting and art direction, not reliable maps or spawn charts.', 'Lighting, object placement, and effects can change through Early Access.'], image: { src: '/images/maps/castle-exterior.png', alt: 'Official Castle exterior in green fog', caption: 'Official EA Castle establishing shot' } },
      { id: 'threats', heading: 'Hazards and threat identification', paragraphs: ['The Castle can contain current threats, but no checked source provides a complete Castle-specific spawn matrix. Use behavior cues and preserve transport access instead of memorizing an unsupported roster.', 'The Ear’s official image is set in a Castle-like interior, while exact spawn rates remain unknown.'], links: links(['/monsters', 'Open Monsters'], ['/tools/monster-finder', 'Use observed clues']) },
    ],
    faqs: [
      { question: 'Is Castle a current map?', answer: 'Yes. It is named in the official Early Access launch announcement.' },
      { question: 'Does Castle have elevators?', answer: 'The official announcement says elevators and funiculars help players move around it.' },
      { question: 'Is Mansion definitely the same as Castle?', answer: 'The checked sources do not justify treating every Mansion note as a Castle-wide fact.' },
    ],
    sourceIds: ['S11', 'S14', 'S15', 'S17'],
    related: standardRelated([
      ['/maps', 'Maps hub', 'Compare current and historical locations.'],
      ['/loot-and-extraction', 'Loot & extraction', 'Plan heavy-object recovery.'],
      ['/monsters', 'Monsters', 'Use current behavior evidence.'],
      ['/maps/ship', 'Ship guide', 'Compare the other current location.'],
    ]),
  },
  {
    route: '/monkey-cart',
    title: 'Last Pirates Monkey Cart & Monkey Porter Guide — Price, Upgrade & Delivery',
    h1: 'Monkey Cart and Monkey Porter Guide',
    description: 'Current Monkey Cart and Monkey Porter evidence: the 800-to-200 cart change, one-level Porter duration, delivery spending, respawn change, and cart/funicular fix.',
    eyebrow: 'Hauling system · current patches',
    directAnswer: [
      'The current patch history records Monkey Cart changing from 800 to 200. It also says Monkey Porter lasts one level, is spent when delivery is completed rather than when it dies, and no longer respawns automatically every level.',
      'The official launch announcement describes a Monkey Assistant that follows with its own cart, collects small loot, and returns it to the boat. An Aug 20 fix also addresses a cart/funicular problem; exact upgrade stats and every live price remain build-sensitive.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Items & Weapons', href: '/items-and-weapons' }, { label: 'Monkey Cart' }],
    heroImage: { src: '/images/items/cart-cannon-kraken.png', alt: 'Official cart cannon facing a Kraken', assetId: 'cart-cannon-kraken-official' },
    sections: [
      { id: 'cart', heading: 'Monkey Cart current price change', paragraphs: ['The official patch record changes Monkey Cart from 800 to 200. This page preserves the direction and published values with the patch date rather than treating 200 as an eternal economy constant.', 'Check the current store after later updates, especially because solo and team shop tuning is now separate.'], links: links(['/solo-guide', 'Understand separate solo shop tuning']) },
      { id: 'porter', heading: 'What Monkey Porter does', paragraphs: ['The launch announcement describes a Monkey Assistant that follows with its own cart, picks up small loot, and runs it back to the boat. Later patch wording uses Monkey Porter and defines its lifecycle.', 'The evidence supports delivery assistance, not a claim that it handles every item size, path, or hazard.'] },
      { id: 'lifecycle', heading: 'One level, spent on delivery', paragraphs: ['Current patch notes say Porter lasts for one level and is spent on delivery, not death. They also say it no longer respawns every level.', 'Those distinctions matter when reading older advice: a Porter disappearing after a completed delivery is not the same event as dying, and launch behavior should not be assumed after the fix.'], table: { headers: ['Field', 'Current official wording'], rows: [['Duration', 'One level'], ['Spent', 'On delivery, not death'], ['Respawn', 'No longer every level']] } },
      { id: 'upgrades', heading: 'Cart upgrades in the launch build', paragraphs: ['The launch post names Organizer, Deeper Cart, and Cart Cannon as examples in the upgraded cart system. It does not publish a complete upgrade tree or exact numeric modifiers.', 'The official media shows a cart cannon facing a Kraken, which is valid visual context but not a damage test.'] },
      { id: 'funicular', heading: 'Cart and funicular fix', paragraphs: ['An Aug 20 hotfix addresses the cart/funicular interaction. This is relevant to Castle transport, while the source does not justify a full mechanical walkthrough or guarantee against every future collision issue.', 'Keep the cart centered, avoid crowding moving transport, and record the build if a repeatable transport fault remains.'], links: links(['/maps/castle', 'Read verified Castle transport context']) },
      { id: 'hauling', heading: 'Use it in the current hauling loop', paragraphs: ['Large objects became about 26% lighter on Aug 26, while the Porter description focuses on small loot. Combine tools by item type instead of assuming the assistant replaces manual heavy hauling.', 'The loot guide covers breakable valuables, route staging, and performance context for loot-heavy scenes.'], image: { src: '/images/items/hauling-cart.png', alt: 'Official hauling cart beside the shore', caption: 'Official EA hauling cart media' }, links: links(['/loot-and-extraction', 'Open Loot & Extraction'], ['/performance', 'Diagnose loot-heavy frame drops']) },
    ],
    faqs: [
      { question: 'What happened to the Monkey Cart price?', answer: 'An official hotfix changed it from 800 to 200; later builds can still retune it.' },
      { question: 'How long does Monkey Porter last?', answer: 'The current patch wording says one level.' },
      { question: 'When is Porter spent?', answer: 'On delivery, not on death, according to the official patch.' },
    ],
    sourceIds: ['S11', 'S13', 'S14', 'S16', 'S17'],
    related: standardRelated([
      ['/items-and-weapons', 'Items & weapons', 'Return to the current item hub.'],
      ['/loot-and-extraction', 'Loot & extraction', 'Plan hauling and return routes.'],
      ['/maps/castle', 'Castle guide', 'See current funicular context.'],
      ['/solo-guide', 'Solo guide', 'Adapt hauling without crew coverage.'],
    ]),
  },
  {
    route: '/performance',
    title: 'Last Pirates FPS & Performance Fixes — Low FPS, Stutter & Lag',
    h1: 'Last Pirates: Die Together FPS and Performance Fixes',
    description: 'Safe current FPS troubleshooting for low frame rate, stutter, lag, loot-heavy drops, laptop auto-quality, drivers, file verification, and scene diagnosis.',
    eyebrow: 'Performance · reversible checks',
    directAnswer: [
      'Current official patches include session optimization, general optimization, enemy-spawn warmup, fewer frame drops while hauling lots of loot, coin optimization, and a laptop auto-quality fix. Those changes make patch state the first performance check.',
      'Players still report low FPS even on high-end hardware, but one report is a problem signal rather than a universal benchmark. Update the game, compare preset and auto quality, test resolution/display mode, reduce background load, use normal vendor drivers, verify files, and isolate the scene.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Troubleshooting', href: '/troubleshooting' }, { label: 'Performance' }],
    heroImage: { src: '/images/maps/castle-exterior.png', alt: 'Official foggy Castle exterior scene', assetId: 'castle-exterior-official' },
    sections: [
      { id: 'official', heading: 'What official patches already changed', paragraphs: ['The Aug 19–21 sequence records session and general optimization, enemy-spawn prefab warmup, fewer loot-heavy frame drops, coin optimization, and a laptop auto-quality fix. These are current factual changes, not promises that every PC now holds one target frame rate.', 'The best baseline is a fully updated build with known settings, not a launch-day comparison.'], links: links(['/updates', 'Review the official patch sequence']) },
      { id: 'baseline', heading: '1 · Establish a clean baseline', paragraphs: ['Finish the current Steam update, restart the game, and note the map, scene, crew size, display mode, resolution, quality preset, and whether the drop appears immediately or after a long session.', 'This turns “low FPS” into a repeatable case and separates one heavy scene from a whole-session regression.'] },
      { id: 'quality', heading: '2 · Compare preset and auto quality', paragraphs: ['The Aug 21 notes specifically mention fixing automatic quality selection on laptops. Test the current automatic choice once, then compare one lower preset at the same resolution.', 'Change one variable at a time. If several settings move together, the result cannot identify the expensive layer.'], table: { headers: ['Comparison', 'Question answered'], rows: [['Auto vs known preset', 'Did current auto selection choose poorly?'], ['Same preset, lower resolution', 'Is pixel load dominant?'], ['Windowed/borderless/fullscreen', 'Is display mode part of the symptom?']] } },
      { id: 'system', heading: '3 · Use normal system checks', paragraphs: ['Close unnecessary high-load background work, confirm the game is using the intended GPU on a multi-GPU laptop, and install a normal stable driver from the hardware vendor if yours is clearly outdated.', 'Do not download random DLLs, registry packs, unofficial executables, or unsupported launch-flag bundles. They create risk and make the comparison harder.'], links: links(['/system-requirements', 'Compare official system requirements']) },
      { id: 'files', heading: '4 · Verify installed files', paragraphs: ['If the current client behaves abnormally after updating, use Steam’s installed-files verification and retest the same scene. This is reversible and stays within the supported delivery path.', 'A successful verification does not prove hardware health, but it removes one common client-integrity variable.'] },
      { id: 'scene', heading: '5 · Diagnose the scene', paragraphs: ['Compare an ordinary room with enemy-spawn moments, coin-heavy areas, large loot piles, and long-session play. Official fixes name those workloads, so scene labels make a report useful.', 'If only loot-heavy hauling drops, link the case to route and object count context without claiming an exact universal threshold.'], links: links(['/loot-and-extraction', 'Review loot-heavy hauling context'], ['/maps/ship', 'Ship scene context'], ['/maps/castle', 'Castle scene context']) },
      { id: 'report', heading: '6 · Report a reproducible case', paragraphs: ['Include CPU, GPU, RAM, operating system, resolution, preset, display mode, build/update date, map, crew size, scene, approximate before/after FPS, and whether file verification changed anything.', 'A community post such as “67fps on my 5070ti” signals demand, but a useful diagnosis needs the surrounding variables.'] },
    ],
    faqs: [
      { question: 'Did the game receive performance patches?', answer: 'Yes. Official notes name session, enemy-spawn, loot-heavy, coin, general, and laptop auto-quality work.' },
      { question: 'Should I use random launch flags?', answer: 'No. Use supported settings and reversible comparisons unless an official current source documents a flag.' },
      { question: 'What should a performance report include?', answer: 'Hardware, OS, resolution, preset, display mode, build, map, crew size, scene, FPS behavior, and verification result.' },
    ],
    sourceIds: ['S13', 'S15', 'S16', 'S18'],
    related: standardRelated([
      ['/troubleshooting', 'Troubleshooting hub', 'Choose another current problem path.'],
      ['/system-requirements', 'System requirements', 'Compare the official PC baseline.'],
      ['/loot-and-extraction', 'Loot & extraction', 'Understand loot-heavy scene context.'],
      ['/updates', 'Updates', 'Check later optimization changes.'],
    ]),
  },
  {
    route: '/revive-guide',
    title: 'Last Pirates Revive Guide — Downed Friends, Stamina & Recovery',
    h1: 'How Reviving and Downed Players Work in Last Pirates',
    description: 'A current downed-player guide covering the official 25-second solo and 15-second co-op floor times, player-reported stamina pressure, and safe recovery planning.',
    eyebrow: 'Recovery · facts vs reports',
    directAnswer: [
      'The Aug 26 patch sets floor/downed time to 25 seconds in solo and 15 seconds in co-op. Those are the current exact official values; the checked patch does not publish every pickup, carry, stamina, or revive interaction.',
      'Players report difficulty moving or picking up downed friends when stamina collapses. Treat that as a problem signal: clear the route, stop hauling, assign one rescuer, preserve space, and avoid presenting the community-mentioned booty revival detail as a confirmed mechanic.',
    ],
    buildContext: checked,
    confidence: 'community-reported',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Co-op', href: '/coop' }, { label: 'Revive Guide' }],
    heroImage: { src: '/images/game/feature-coop.webp', alt: 'Official Last Pirates co-op feature art', assetId: 'feature-coop' },
    sections: [
      { id: 'timers', heading: 'Current official floor timers', paragraphs: ['The newest official patch found at research time gives two exact values: solo players remain on the floor for 25 seconds and co-op players for 15 seconds. The wording describes floor time; it does not explain every follow-on state.', 'Use the timer difference for urgency, not as a complete revive specification.'], table: { headers: ['Mode', 'Official Aug 26 floor time'], rows: [['Solo', '25 seconds'], ['Co-op', '15 seconds']] } },
      { id: 'reported', heading: 'Moving downed friends is a player-reported pain point', paragraphs: ['A current Steam Community discussion reports that stamina pressure makes picking up or moving downed friends difficult. This shows a real question players have but does not prove a global bug or one exact stamina formula.', 'Record crew size, build, object load, scene, and what action caused the stamina collapse before escalating.'] },
      { id: 'prepare', heading: 'Prepare the recovery lane', paragraphs: ['Before touching a downed player, stop optional hauling, clear a short route, and keep other crew members from occupying the same narrow lane. One rescuer and one lookout is easier to coordinate than everyone grabbing at once.', 'These are conservative team habits derived from the time pressure, not hidden revive bonuses.'] },
      { id: 'solo', heading: 'Solo recovery context', paragraphs: ['Solo receives ten more seconds of floor time than co-op in the current patch. Separate solo balance also applies to quota, shop context, item counts, and enemy spawns.', 'The longer timer does not guarantee recovery from every position or threat. Protect space before a risky haul and use behavior cues to avoid a second hit.'], links: links(['/solo-guide', 'Open the current solo guide']) },
      { id: 'coop', heading: 'Co-op recovery context', paragraphs: ['Co-op floor time is 15 seconds, so a crew should call the location and threat before committing. Open-deck voice received a fix on Aug 26, while local audio and session problems can still affect communication.', 'If a player disconnects rather than falls, use the reconnect path; do not treat the two states as interchangeable.'], links: links(['/coop', 'Review current co-op context'], ['/save-and-reconnect', 'Use the reconnect guide']) },
      { id: 'unknowns', heading: 'Unverified details stay labeled', paragraphs: ['The checked official sources do not independently confirm the community-described booty revival detail, an exact stamina cost, pickup animation timing, carry speed, invulnerability, or recovery health.', 'This page will only promote one of those details when a current official note or direct verified build evidence supports it.'] },
      { id: 'report', heading: 'Report a repeatable recovery failure', paragraphs: ['Capture mode, crew size, map, build, downed location, nearby threat, whether the player was carrying anything, stamina state, and exact failed action. A short reproducible description is more useful than a broad balance claim.', 'Use the Co-op Troubleshooter for voice, version, lobby, disconnect, and reconnect branches around the same run.'], links: links(['/tools/coop-troubleshooter', 'Open the Co-op Troubleshooter'], ['/updates', 'Check current fixes']) },
    ],
    faqs: [
      { question: 'How long are players downed?', answer: 'The Aug 26 patch says 25 seconds in solo and 15 seconds in co-op.' },
      { question: 'Is moving friends a confirmed stamina bug?', answer: 'It is a player-reported pain point, not a confirmed universal bug or published formula.' },
      { question: 'Is the booty revival detail official?', answer: 'Not in the checked current official sources, so it remains explicitly unverified.' },
    ],
    sourceIds: ['S17', 'S18'],
    related: standardRelated([
      ['/troubleshooting', 'Troubleshooting hub', 'Choose the relevant recovery path.'],
      ['/coop', 'Co-op guide', 'Coordinate current crew sessions.'],
      ['/tools/coop-troubleshooter', 'Co-op Troubleshooter', 'Generate a safe checklist.'],
      ['/solo-guide', 'Solo guide', 'Use the current 25-second context.'],
    ]),
  },
  {
    route: '/tools',
    title: 'Last Pirates Tools — Monster Finder, Co-op Fixes & Run Tracker',
    h1: 'Last Pirates: Die Together Tools',
    description: 'Open the transparent Monster Finder, source-backed Co-op Troubleshooter, and local-only Run & Chapter Tracker for Last Pirates: Die Together.',
    eyebrow: 'Three transparent utilities',
    directAnswer: [
      'This tools hub contains three focused utilities: a rule-based Monster Finder, a deterministic Co-op Troubleshooter, and a personal Run & Chapter Tracker stored only in your browser.',
      'None of the tools uses an LLM to guess game facts, reads game save files, changes network or security settings, or sends tracker notes to a server. Each explains its evidence boundary before you act on the result.',
    ],
    buildContext: checked,
    confidence: 'confirmed',
    breadcrumbs: [{ label: 'Home', href: '/' }, { label: 'Tools' }],
    heroImage: { src: '/images/game/steam-header.jpg', alt: 'Official Last Pirates Steam header art', assetId: 'steam-header' },
    sections: [
      { id: 'finder', heading: 'Monster Finder', paragraphs: ['Select observed behavior such as sound reaction, disguise, disturbance, pull sound, knockback context, or rat-group behavior. The finder returns only records whose typed tags match all selected clues.', 'Every match shows why it matched, the evidence state, the latest stored patch change, and a detail or hub link.'], links: links(['/tools/monster-finder', 'Open Monster Finder']) },
      { id: 'coop', heading: 'Co-op Troubleshooter', paragraphs: ['Choose the symptom, host or joiner role, connection method, lobby visibility, version state, and Steam online state. The result is an ordered safe checklist.', 'Official steps carry evidence labels; standard steps are reversible. The tool rejects destructive save, random firewall, registry, and download advice.'], links: links(['/tools/coop-troubleshooter', 'Open Co-op Troubleshooter']) },
      { id: 'tracker', heading: 'Run & Chapter Tracker', paragraphs: ['Record run name, solo/co-op mode, map, day, chapter, crew notes, monsters, loot, and a checklist. Data stays in localStorage in this browser.', 'You can edit, delete, reset, export, and import validated JSON. It is a notebook, not a game-save reader.'], links: links(['/tools/run-chapter-tracker', 'Open Run & Chapter Tracker']) },
      { id: 'privacy', heading: 'Local and transparent by design', paragraphs: ['Tracker records do not require an account or database. Export is initiated by you; import validates structure before replacing the local list.', 'Advertising follows the site’s existing CMP and route eligibility, and no ad is placed inside tool controls or between an input and its result.'], links: links(['/privacy', 'Read the site privacy policy']) },
      { id: 'evidence', heading: 'Evidence states are visible', paragraphs: ['Official current facts, historical patch facts, community problem signals, and unknown fields are not blended together. This matters most when an error label or player observation could have several causes.', 'Use durable article pages for deeper sources and patch history after a tool narrows the question.'], links: links(['/updates', 'Open the canonical update timeline'], ['/faq', 'Read current short answers']) },
      { id: 'choose', heading: 'Choose the smallest useful tool', paragraphs: ['Use Monster Finder for “what did I see,” Co-op Troubleshooter for “why can’t the crew connect or recover,” and Run Tracker for “where did this personal run leave off.”', 'If your question is about current maps, items, solo balance, or performance, start from the related editorial hub instead of forcing it through an unrelated form.'], links: links(['/monsters', 'Monsters'], ['/coop', 'Co-op'], ['/troubleshooting', 'Troubleshooting']) },
    ],
    faqs: [
      { question: 'Do the tools send my tracker notes to a server?', answer: 'No. The Run Tracker stores records in localStorage in the current browser.' },
      { question: 'Does Monster Finder guess?', answer: 'No. It applies transparent all-selected-clues rules to a typed registry.' },
      { question: 'Can the troubleshooter change my system?', answer: 'No. It only presents safe ordered checks and does not execute changes.' },
    ],
    sourceIds: ['S11', 'S16', 'S17'],
    related: standardRelated([
      ['/tools/monster-finder', 'Monster Finder', 'Identify threats from behavior.'],
      ['/tools/coop-troubleshooter', 'Co-op Troubleshooter', 'Build a safe connection checklist.'],
      ['/tools/run-chapter-tracker', 'Run Tracker', 'Keep local personal run notes.'],
      ['/troubleshooting', 'Troubleshooting hub', 'Read current problem guides.'],
    ]),
  },
];
